### ISSUE TITLE
Team JAR file upload seems broken

### ISSUE THREAD

**Issue by ruudgreven** [ruudgreven/robocodecup#29]
I received a 500 error (but no logging on the server) when I try to upload a teamfile. This issue is probably related to #14.

The best option I think is:
- Upload the file to upload/**competition_id**/**teamname**.jar.

**Comment by ruudgreven** [comment]
When the above thing is done I can possibly add the checks, because i've already done that once in the robocode-runner project, this is issue #19

**Comment by ruudgreven** [comment]
Still doesn't work. Not even after commit https://github.com/ruudgreven/robocodecup/commit/ab325a2b91d94222f69e8098930bd50bc35bbf01

Help!!!! ;-)

**Comment by TimothySealy** [comment]
Sorry about that. The issue is with the following. When uploading the teams the secret is supplied as a number. In the model definition it is defined as a string. In the database it si however stored as a number breaking the query for finding a team by the secret.

Solution 1: Update the database to make the secret a string (in the team upload file).
Solution 2: Update the model and query to search for secret of type number.

I choose the first solution so updating the teams will probably work.

**Comment by ruudgreven** [comment]
Doh!
